# Generated by Django 2.2.3 on 2019-07-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20190721_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=2),
        ),
        migrations.AddField(
            model_name='teacher',
            name='student_ids',
            field=models.ManyToManyField(to='school.Student'),
        ),
    ]
